package error_scenarios

main :: fn() {
    x : int[..]
    for foo, in x {
        
    }
}
